# Generated by Django 2.0.3 on 2018-03-29 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='baseObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rugbyPoolApp.baseObject')),
                ('opposition', models.CharField(max_length=200)),
                ('kick_off_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('opposition_score', models.IntegerField(default=0)),
                ('our_score', models.IntegerField(default=0)),
            ],
            bases=('rugbyPoolApp.baseobject',),
        ),
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rugbyPoolApp.baseObject')),
                ('our_score', models.IntegerField(default=0)),
                ('opposition_score', models.IntegerField(default=0)),
                ('prediction_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugbyPoolApp.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('rugbyPoolApp.baseobject',),
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rugbyPoolApp.baseObject')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            bases=('rugbyPoolApp.baseobject',),
        ),
        migrations.AddField(
            model_name='match',
            name='match_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugbyPoolApp.series'),
        ),
    ]
